include:
  - source: ../dspace-angular/docker/docker-compose.yml
    project_directory: ../dspace-angular
  - source: ../dspace-angular/docker/docker-compose-rest.yml
    project_directory: ../dspace-angular

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_dspace
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dspace.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - d9_dspacenet

volumes:
  pgadmin-data:

networks:
  d9_dspacenet:
    external: true
